# Custom Language File for Launcher Customizer

[ejs.app]
title = "Launcher d'Interville"

[ejs.landing]
mediaTwitchURL  = "https://www.twitch.tv/obeprod"
mediaTwitterURL = "https://x.com/_ObeProd"
mediaYouTubeURL = "https://www.youtube.com/channel/UCZqVPLPjKdhBnaCsyPN8Sfg"
mediaDiscordURL = "https://discord.gg/2KbcbbunvD"
mediaTiktokURL  = "https://www.tiktok.com/@obeprod"

[ejs.settings]
sourceGithubLink = "https://github.com/EnditTeam/Interville-Launcher"
supportLink = "https://github.com/EnditTeam/Interville-Launcher/issues"

[ejs.welcome]
welcomeHeader = ""
welcomeDescription = ""
welcomeDescCTA = ""
